# Generated by Django 5.1.1 on 2025-01-30 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sch_profile',
            fields=[
                ('School_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('School_Name', models.CharField(blank=True, max_length=50)),
                ('School_Address', models.CharField(blank=True, max_length=50)),
                ('School_District', models.CharField(blank=True, max_length=50)),
                ('School_State', models.CharField(blank=True, max_length=50)),
                ('School_Zipcode', models.CharField(blank=True, max_length=6)),
                ('School_Affiliation_number', models.CharField(blank=True, max_length=50)),
                ('School_Phone_number', models.CharField(blank=True, max_length=50)),
                ('School_Landline_number', models.CharField(blank=True, max_length=50)),
                ('School_IsPublic', models.CharField(blank=True, max_length=10)),
                ('School_IsAtl', models.CharField(blank=True, max_length=10)),
                ('School_IsPmshri', models.CharField(blank=True, max_length=10)),
                ('School_IsTinkering', models.CharField(blank=True, max_length=10)),
                ('School_IsPreviousEng', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
