# Generated by Django 5.1.1 on 2025-01-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sch_profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
