# Generated by Django 5.1.1 on 2025-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_profile', '0002_sch_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sch_profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='sch_profile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
