# Generated by Django 5.1.1 on 2025-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(blank=True, max_length=50)),
                ('Event_des_short', models.CharField(blank=True, max_length=200)),
                ('Event_des_long', models.CharField(blank=True, max_length=1000)),
                ('Event_Head', models.CharField(blank=True, max_length=50)),
                ('Event_Team', models.CharField(blank=True, max_length=2000)),
                ('Contact_Phone_number1', models.CharField(blank=True, max_length=50)),
                ('Contact_Email1', models.CharField(blank=True, max_length=50)),
                ('Contact_Phone_number2', models.CharField(blank=True, max_length=50)),
                ('Contact_Email2', models.CharField(blank=True, max_length=50)),
                ('Pre_Registered', models.BooleanField(default=False)),
                ('Number_Registered', models.IntegerField(default=0)),
                ('Space_Location', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
