# Generated by Django 5.1.1 on 2025-01-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
