# Generated by Django 5.1.1 on 2025-02-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_event_category'),
        ('sch_profile', '0003_remove_sch_profile_verified_sch_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('RegisterEvent_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RStudent_Num', models.IntegerField(default=0)),
                ('REvent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('RSchool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sch_profile.sch_profile')),
            ],
        ),
    ]
