# Generated by Django 5.1.1 on 2025-02-01 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_category'),
        ('register_event', '0001_initial'),
        ('sch_profile', '0003_remove_sch_profile_verified_sch_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerevent',
            name='REvent',
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='RSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_profile.sch_profile'),
        ),
        migrations.AddField(
            model_name='registerevent',
            name='REvent',
            field=models.ManyToManyField(to='event.event'),
        ),
    ]
