# Generated by Django 5.1.1 on 2025-02-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_category'),
        ('register_event', '0002_remove_registerevent_revent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerevent',
            name='REvent',
        ),
        migrations.AddField(
            model_name='registerevent',
            name='REvent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
