# Generated by Django 5.1.1 on 2025-02-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_category'),
        ('register_event', '0004_alter_registerevent_revent'),
        ('sch_profile', '0003_remove_sch_profile_verified_sch_profile_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registerevent',
            unique_together={('REvent', 'RSchool')},
        ),
    ]
